# Generated by Django 4.1.2 on 2023-12-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("job_title", models.CharField(max_length=50)),
                ("employment_status", models.CharField(max_length=50)),
                ("sub_unit", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
